# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main  # Define a branch principal que deve acionar o pipeline

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - script: |
      git config --global user.email "josedavi100@gmail.com"
      git config --global user.name "StrJosedavi"
      git checkout $(Build.SourceBranch)
      git fetch origin pull/$(System.PullRequest.PullRequestNumber)/merge:pullrequest/$(System.PullRequest.PullRequestNumber)/merge
      git merge pullrequest/$(System.PullRequest.PullRequestNumber)/merge --no-edit
      git push origin $(Build.SourceBranch)
    displayName: 'Sync Pull Request'