# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - script: |
      git config --global user.email "josedavi100@gmail.com"
      git config --global user.name "StrJosedavi"
      git pull origin pull/$(System.PullRequest.PullRequestId)/merge
      git push origin $(Build.SourceBranchName)
    displayName: 'Sync Pull Request'